name: Manually deploy
on:
  repository_dispatch:
    types: [updated_post]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    # ここで環境を指定
    environment: 
      name: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Node.js 20に対応した最新バージョンを使用

      - name: Setup node
        uses: actions/setup-node@v4  # Node.js 20に対応した最新バージョンを使用
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
       
      - name: Debug
        run: |
          echo "Bucket: ${{ secrets.AWS_S3_BUCKET }}"
          echo "CF ID: ${{ secrets.AWS_CF_ID }}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 s3://${{ secrets.AWS_S3_BUCKET }} --delete
          echo "AWS CF reset"
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
